Intro pytorch  
torch index problem

In [ ]:
import torch 
example_tensor = torch.tensor([
    [[1,2],[3,4]],
    [[5,6],[7,8]],
    [[9,0],[1,2]]
])
print(example_tensor)
print(example_tensor[0],"\n",
      example_tensor[0,1,1],"\n",
      example_tensor[0,1,1].item())
print(example_tensor[:,0,0])
print(example_tensor[1,:,0])

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]],

        [[9, 0],
         [1, 2]]])
tensor([[1, 2],
        [3, 4]]) 
 tensor(4) 
 4
tensor([1, 5, 9])
tensor([[5, 6],
        [7, 8]])


Tensor Properties: Device

In [ ]:
#看设备
print(example_tensor.device)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
#送入gpu
example_tensor_gpu = example_tensor.to(device)
print(example_tensor_gpu.device)

cpu
cuda
cuda:0


Tensor Properties: Shape

In [ ]:
#shape是属性 size()是方法
print(example_tensor.shape)
print(example_tensor.size())
print(example_tensor.shape[0])
print(example_tensor.size(1))
print(len(example_tensor.shape), len(example_tensor.size()))

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])
3
2
3 3


Initializing Tensors:  
torch.ones_like: creates a tensor of all ones with the same shape and device as example_tensor.  
torch.zeros_like: creates a tensor of all zeros with the same shape and device as example_tensor  
torch.randn_like: creates a tensor with every element sampled from a Normal (or Gaussian) distribution with the same shape and device as example_tensor  


In [39]:
tensor1 = torch.ones_like(example_tensor)
tensor0 = torch.zeros_like(torch.tensor([[2,2]]))
print(tensor1,tensor0)

tensor_radn = torch.randn(3,3,2)
tensor_zero = torch.zeros((2,2))
print(tensor_radn, tensor_zero)

tensor([[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]) tensor([[0, 0]])
tensor([[[-0.3644, -0.4632],
         [ 0.4355,  1.0704],
         [-0.0189,  1.1808]],

        [[-1.1978, -0.5381],
         [ 0.9872, -0.6013],
         [ 0.7135,  0.3791]],

        [[-0.1209,  0.0338],
         [ 0.0120, -0.8819],
         [ 0.3226,  1.1315]]]) tensor([[0., 0.],
        [0., 0.]])


Basic Functions

In [40]:
(example_tensor - 5) * 2

tensor([[[ -8,  -6],
         [ -4,  -2]],

        [[  0,   2],
         [  4,   6]],

        [[  8, -10],
         [ -8,  -6]]])

In [ ]:
print("Mean:", example_tensor.float().mean())
print("Stdev:", example_tensor.float().std())
print(example_tensor.float())
#dim -> 在某一个维度进行压缩
print(example_tensor.float().mean(dim=0))
print(example_tensor.float().mean(dim=1))
print(example_tensor.float().mean(dim=2))

Mean: tensor(4.)
Stdev: tensor(2.9848)
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]],

        [[9., 0.],
         [1., 2.]]])
tensor([[5.0000, 2.6667],
        [3.6667, 4.6667]])
tensor([[2., 3.],
        [6., 7.],
        [5., 1.]])
tensor([[1.5000, 3.5000],
        [5.5000, 7.5000],
        [4.5000, 1.5000]])


PyTorch Neural Network Module (torch.nn)  
nn.BatchNorm1d 是干啥的？   
本质：批归一化（Batch Normalization） 技术，作用是让每个批次的输入数据，在训练时保持 一致的均值和标准差 。  

In [ ]:
import torch.nn as nn
linear = nn.Linear(10,2)
example_input = torch.rand(5,10)
example_out = linear(example_input)
print(example_out)
relu = nn.ReLU()
#如果是图像（二维张量），要用 nn.BatchNorm2d ；视频（三维张量）用 nn.BatchNorm3d 。
BN = nn.BatchNorm1d(2) #2表示特征的个数
print(relu(example_out))
print(BN(relu(example_out)))

tensor([[-0.0057,  0.0465],
        [-0.0247,  0.1291],
        [ 0.1586, -0.1041],
        [ 0.1054,  0.2207],
        [-0.0208,  0.1896]], grad_fn=<AddmmBackward0>)
tensor([[0.0000, 0.0465],
        [0.0000, 0.1291],
        [0.1586, 0.0000],
        [0.1054, 0.2207],
        [0.0000, 0.1896]], grad_fn=<ReluBackward0>)
tensor([[-0.7893, -0.8461],
        [-0.7893,  0.1431],
        [ 1.5816, -1.4032],
        [ 0.7864,  1.2393],
        [-0.7893,  0.8669]], grad_fn=<NativeBatchNormBackward0>)


nn.Sequential  
nn.Sequential creates a single operation that performs a sequence of operations. For example, you can write a neural network layer with a batch normalization as

In [63]:
mlp_layer = nn.Sequential(
    nn.Linear(5,2),
    nn.BatchNorm1d(2),
    nn.ReLU()
)
test_input = torch.rand(5,5) + 1
print(mlp_layer(test_input))

tensor([[1.0374, 0.0000],
        [0.0000, 0.7015],
        [0.4990, 0.8359],
        [0.0813, 0.9053],
        [0.2766, 0.0000]], grad_fn=<ReluBackward0>)


Optimization  
To create an optimizer in PyTorch, you'll need to use the torch.optim module, often imported as optim. optim.Adam corresponds to the Adam optimizer.   To create an optimizer object, you'll need to pass it the parameters to be optimized and the learning rate, lr, as well as any other parameters specific to the optimizer.  

For all nn objects, you can access their parameters as a list using their parameters() method, as follows:  

In [65]:
import torch.optim as optim
adam_opt = optim.Adam(mlp_layer.parameters(),lr=0.01)

d:\Anaconda\envs\YOLO\lib\site-packages\onnxscript\converter.py:823: FutureWarning: 'onnxscript.values.Op.param_schemas' is deprecated in version 0.1 and will be removed in the future. Please use '.op_signature' instead.
  param_schemas = callee.param_schemas()
d:\Anaconda\envs\YOLO\lib\site-packages\onnxscript\converter.py:823: FutureWarning: 'onnxscript.values.OnnxFunction.param_schemas' is deprecated in version 0.1 and will be removed in the future. Please use '.op_signature' instead.
  param_schemas = callee.param_schemas()


Training Loop  
A (basic) training step in PyTorch consists of four basic parts:  

1.Set all of the gradients to zero using opt.zero_grad()  
2.Calculate the loss, loss  
3.Calculate the gradients with respect to the loss using loss.backward()  
4.Update the parameters being optimized using opt.step()  
That might look like the following code (and you'll notice that if you run it several times, the loss goes down):  

In [ ]:
train_example = torch.rand(100,5) + 1
adam_opt.zero_grad()
#想局部切断用 detach()，想全局禁用梯度用 torch.no_grad() 。
cur_loss = torch.abs(1 - mlp_layer(train_example)).mean()
cur_loss.backward()
adam_opt.step()
print(cur_loss)

tensor(0.7563, grad_fn=<MeanBackward0>)
